security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: "%admin_password%"
                        roles: 'ROLE_ADMIN'
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            # form_login: ~

    access_control:
        - { path: ^/админ, roles: ROLE_ADMIN }
