# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.markdown:
        class: AppBundle\Utils\Markdown

    app.twig.app_extension:
        class:     AppBundle\Twig\MarkdownExtension
        arguments: ['@app.markdown']
        public:    false
        tags:
            - { name: twig.extension }
